### ISSUE TITLE
Unable to View/Verify Safety Numbers?

### ISSUE THREAD

**Issue by colvdv** [alexlance/signal-android-classic#11]
When I go to verify safety number I am greeted with a message saying "You must first exchange messages in order to view safety number."

![Screenshot_20240301-195430.png](https://github.com/alexlance/signal-android-classic/assets/122833328/449a9794-96b4-463f-8a14-7ef28541173d)

Messages have been exchanged, though only briefly.

**Comment by colvdv** [comment]
This is not the case on the other end, which is using Molly-FOSS, another Signal fork. Safety number can be from that side, no issues.

This is an important issue to address for confidence to be gained regarding the safety of this Signal fork.

**Comment by alexlance** [comment]
Thanks for the bug report - when I go to "Chat Settings -> View Safety Number" for a contact, a QR code appears and 60 digits appear. This happens with contacts that are Signal only or contacts that are SMS only. I.e. I can't replicate what you're seeing.

I don't have any contacts that use Molly - maybe that's the problem? Do all your contacts have this problem you're describing - or only your Molly contacts?

One thing you could try is to load up the error page - then go to "Settings -> Help -> Debug log" and see if there are some errors towards the bottom of the log.

**Comment by colvdv** [comment]
Okay, figured it out. Your insight made the difference. The issue was that it was a Signal only contact; I didn't have the contact saved on the phone otherwise.

So, to fix this, I created a new contact and added the phone number to it.

Searching up the number to send a new message it comes up Unknown. Adding the phone number to device contacts fixes this also.

 All good now, thanks!
