### ISSUE TITLE
Forcing Unsecured SMS even though the number is registered with Signal?

### ISSUE THREAD

**Issue by colvdv** [alexlance/signal-android-classic#12]
I have a contact on my phone that uses Signal. In Molly-FOSS we can message securely, all good.

This same contact, this signal-android-classic fork is not giving the option to chat securely. It is forcing unsecured SMS for some reason. This is me attempting to message them first. I will have them attempt to message me first and report back with my findings.

**Comment by colvdv** [comment]
Okay, they sent me a message and it comes up Unknown.

![Screenshot_20240302-152032.png](https://github.com/alexlance/signal-android-classic/assets/122833328/cf0abe55-9731-4d14-808b-476b6ad4fd88)

Weird. Then I reply and then they reply to that and all of a sudden I can see their profile name & picture, but it doesn't link the contact from my phone, despite having it in there, same phone number.

![Screenshot_20240302-152433.png](https://github.com/alexlance/signal-android-classic/assets/122833328/c14f892b-a1b6-48ee-a26f-8f776f5cbfe1)

They are using Molly on their end.

**Comment by colvdv** [comment]
Then I had them use the OG Signal app, and this happens (different phone number than they have on Molly, but is in my contacts already):

![Screenshot_20240302-153557.png](https://github.com/alexlance/signal-android-classic/assets/122833328/dfadf4d1-50e5-4d88-8d5d-70bf10d8190d)

I try to reply and it just shows a spinning circle, not sending.

**Comment by alexlance** [comment]
I fetched the latest stable APK from the Signal website (6.47.5). I then installed it on a secondary phone. My two phones: one running normal Signal, one running this repo's Signal, were both able to communicate with each other like normal.

Would you happen to know if your friend downloaded and installed the most recent Signal APK from the normal Signal place:  https://signal.org/android/apk/  or were they perhaps using an older version of Signal or something?

I wonder what's happening here.

**Comment by alexlance** [comment]
I tried the same thing with Molly and it all seemed good. That is, messages between this repo's Signal and Molly went through to each other ok. I'll keep looking though. Molly version: v6.47.4-1-FOSS.

**Comment by colvdv** [comment]
He said he is on the most recent Signal build, updated to be sure. Molly running the most recent build also. I'm not sure what to make of it. It should be noted that we are both using GrapheneOS, not sure if that matters. His doesn't have Google Play Services, mine does.

**Comment by alexlance** [comment]
Ah nice - I'm running: https://lineage.microg.org/ which is pretty good too. But I've heard good things about Graphene too.

I wonder if the mobile numbers and the Signal accounts are a bit at odds with each other. 

For example you mentioned your friend has a couple of numbers - I wonder if eg, their Signal account originally got associated with number1, but then later you're trying to reach out to him on number2. That sort of thing. 

If you create a new mobile contact, and give it the phone number2, and then try and message him using that contact (one might have to remove number2 from his original contact too).

**Comment by colvdv** [comment]
I already have him saved as 2 separate contacts, one for each number, so I don't think that is the case.

Honestly I think I'll just bite the bullet on this one and stick with Molly. Who needs SMS anyways? 90% of my contacts are on Signal anyhow, the others I don't converse with over the phone, just brief messages.

There was another issue on my Grandpa's phone where it wasn't showing SMS contacts, only Signal contacts (me), despite all permissions being there. I tried to figure it out but no luck.

I love what you're doing and the whole idea but its turning out to be more of a hassle than it's worth to me, maybe due to GrapheneOS, which has been amazing in the year I've used it.

**Comment by alexlance** [comment]
Yep totally get it - will close issue for now - feel free to re-open if more info surfaces.

Also worth noting that this repo was intended to help one build their own version of Signal, rather than become the canonical focal point for a new fork. 

Molly looks really good. I wonder if one could offer them a PR for (optional) SMS/MMS support :)

**Comment by colvdv** [comment]
> Molly looks really good. I wonder if one could offer them a PR for (optional) SMS/MMS support :)

They've openly expressed that SMS support won't be added because it is opposite their focus. I totally get it. From a security standpoint, adding SMS support isn't worth it. Better to get everyone to switch and open their awareness than to make it convenient and keep people unconsciously secure.

I found a post where someone had even submitted a pull request for SMS support for Molly, but it was rejected, lol. It boils down to choosing to be secure.

**Comment by alexlance** [comment]
Got a link to the post that you mentioned? (There doesn't appear to be an open or closed PR on the mollyim github regarding SMS support).

**Comment by colvdv** [comment]
I cant find it now. I swear I saw a thread where someone blew up about it "Are you kidding me?!", but now I can't find it.

But if you search SMS in Molly's issues you can see that they close all SMS support requests as not-planned.
