### ISSUE TITLE
How to take a new release?

### ISSUE THREAD

**Issue by Particpant** [alexlance/signal-android-classic#3]
Do we need to back up/restore again to take new releases, or if we're already using this build, can we sideload on top of the existing one?

**Comment by alexlance** [comment]
The first time you install one of the APKs from the releases page, one needs to perform the whole process of making a backup, and restoring the backup into the new version.

BUT once that initial installation is performed, subsequent installations (upgrades) can be made by just clicking the latest APK from the releases tab, from your phone. Android will then ask you if you want to upgrade and it's basically a one-click upgrade.

**Comment by Particpant** [comment]
Thanks!
