### ISSUE TITLE
SMS sending issues

### ISSUE THREAD

**Issue by bhsane** [alexlance/signal-android-classic#4]
It seems on the latest release, v6.19.2, outgoing sms messages no longer send. The sending circle is perpetually spinning.

Edit: I changed to the built in sms app and then back to signal and now it's working again.

Sorry about the false alarm.

Thanks for doing this. I managed to keep several family members using this rather than transferring everything out of signal and to their default sms app and get them to learn something new that they'll constantly have trouble with.

I also use the app obtanium to point to this github and keep the app updated.

**Comment by alexlance** [comment]
Hi there - that's great to hear.
Might kick off another round of builds today :)
